// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-aerial-red-brick-latvia.jpg', cap:'Turaida loss, punastest tellistest keskaegne kindlus Gauja kohal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-exterior-red-walls-latvia.jpg', cap:'Cēsise loss, Liivi ordu residents Vidzemes'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-bend-aerial-valley-latvia.jpg', cap:'Gauja jõe käänak, Gauja oru rahvuspark'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-cable-car-gauja-valley-latvia.jpg', cap:'Sigulda köisraudtee üle Gauja oru kaljude'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-baker-artisan-bread-latvia.jpg', cap:'Pagar Cēsu Maize pagariäris sõtkumas traditsioonilist rukkileiba'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-sign-artisan-bread-latvia.jpg', cap:'Cēsu Maize, kohalik leib, küpsetatud siinsamas'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-guests-bakery-tasting-latvia.jpg', cap:'Külalised maitsmas värsket leiba pagariäri leti ääres'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-guests-exploring-latvia.jpg', cap:'Külalised avastamas Turaida lossi siseõue'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-walls-autumn-latvia.jpg', cap:'Cēsise lossi müürid sügislehtede raamis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-sunset-valley-latvia.jpg', cap:'Gauja org päikeseloojangul'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-reflection-water-latvia.jpg', cap:'Cēsise loss peegeldumas talvises tiigis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-barefoot-baltic-van-winter-latvia.jpg', cap:'Barefoot Balticu mikrobuss talvel'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-misty-dawn-autumn-latvia.jpg', cap:'Gauja jõgi koidikul kerkiva uduga'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-bobsleigh-track-autumn-latvia.jpg', cap:'Sigulda olümpia bobi rada sügisel'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-windmill-stone-archway-latvia.jpg', cap:'Vidzeme tuulik kiviväravast nähtuna'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-orthodox-church-blue-domes-latvia.jpg', cap:'Sinikuplitega õigeusu kirik Vidzeme maapiirkonnas'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-st-johns-church-spire-latvia.jpg', cap:'Cēsise Püha Johannese kirik'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-autumn-forest-latvia.jpg', cap:'Cēsise loss sügismetsa raamis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-wooden-forest-stairs-latvia.jpg', cap:'Puidust metsatrepid Gauja orus'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/latvia-white-stork-nest-countryside.jpg', cap:'Läti valge-toonekure pesa, riigi rahvuslind'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-heritage-historic-photo-latvia.jpg', cap:'Cēsise pärand, ajalooline kohalik foto'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-rapeseed-field-spring-latvia.jpg', cap:'Õitsev rapsipõld, kevad Gauja orus'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-gateway-guest-latvia.jpg', cap:'Külaline Turaida lossi väraval'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-01-latvia.jpg', cap:'Lähenemine Turaida lossi puidust väravale'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Turaida lossi siseõues'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-15-latvia.jpg', cap:'Turaida lossi kivimüürid'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-20-latvia.jpg', cap:'Turaida lossi kompleks muuseumikaitseala seestpoolt'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-1-latvia.jpg', cap:'Turaida rahvalaulude küngas (Dainu Kalns)'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Krišjānis Baronsi auks püstitatud skulptuurid Rahvalaulude künkal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Gauja oru jalutusrajad Velnu klintsi (Kuradikalju) lähedal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-3-latvia.jpg', cap:'Metsarada piki Gauja orgu'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-01-latvia.jpg', cap:'Sigulda Uus loss ja seda ümbritsev park'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Rada Sigulda lossi keskaegsete varemete juurde'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Puidust jalutusrada läbi Krimulda metsa'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-15-latvia.jpg', cap:'Krimulda mõisa piirkond kevadel'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-30-latvia.jpg', cap:'Metsatrepp Krimulda jalutusrajal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-45-latvia.jpg', cap:'Krimulda jalutusraja viimane lõik'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-1-latvia.jpg', cap:'Keskaegne Cēsise loss väljast'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-3-latvia.jpg', cap:'Cēsise lossi kivitorn'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Cēsise lossi sisemus, valgustatud küünlalaternaga'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Kivitöö detail Cēsise lossi sees'},
    ],
    rundale: [
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-white-hall-daiga-guide-latvia.jpg', cap:'Daiga Valges Saalis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-panoramic-view-latvia.jpg', cap:'Vaade Bauska lossi tornist'},
  {src:'https://barefootbaltic.com/images/exc-rundale/barefoot-baltic-guests-minibus-excursion-latvia.jpg', cap:'Külalised minibussis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Suure Ķemeri raba laudtee tumedate rabaveekogude vahel linnuvaates'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Puidust laudtee Ķemeri kõrgsoo vaikse tiigi ääres'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga jutustab Bauska lossis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-guest-portrait-latvia.jpg', cap:'Daiga külalisega lossis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-red-room-baroque-interior-latvia.jpg', cap:'Punane saal Rundāles'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-historical-costumes-reenactment-latvia.jpg', cap:'Ajaloolised kostüümid Bauska lossis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Rundāle lossi paraadtrepp'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-grand-gallery-mirrors-guest-latvia.jpg', cap:'Külaline Suures galeriis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-grand-gallery-daiga-guide-latvia.jpg', cap:'Daiga Suures galeriis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Portselani kabinet Kuldse saali kõrval'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-blue-room-02-latvia.jpg', cap:'Sinine tuba Rundāle lossis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-duke-state-bedroom-5-latvia.jpg', cap:'Hertsogi paraadmagamistuba'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-gilded-trellis-ceiling-green-room-latvia.jpg', cap:'Kullatud võrelagi Rohelises kabinetis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-courland-dukes-genealogy-panel-latvia.jpg', cap:'Kuramaa hertsogite suguvõsa stendi juures'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Rundāle lossi baroksed roosiaiad suvel'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-historic-kitchen-copper-latvia.jpg', cap:'Ajalooline hertsogiköök Bauska lossis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Puidust galerii Bauska lossi tornis'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Külaline Bauska lossi tornis talvel'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guest-vaulted-room-latvia.jpg', cap:'Daiga ja külaline võlvitud ruumis Bauska lossis'},
    ],
    kemeri: [
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-group-walking-trail-latvia.jpg', cap:'Single file across the open bog at golden hour', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-child-cottongrass-latvia.jpg', cap:'Stepping out in bog shoes through the cottongrass', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-solo-walker-pines-latvia.jpg', cap:'A quiet moment out on the bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Autumn colours across the Ķemeri raised bog', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'View from the Ķemeri observation tower', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'The Great Ķemeri Bog from above in spring', credit:'Photo: licensed via iStock'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Last light on a single bog pine', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sunset over the dwarf pines of Ķemeri', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'A bog pool at golden hour', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-portrait-latvia.jpg', cap:'A couple ready for the bog shoe walk', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Heading back through the forest trail', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'A guest in bog shoes out on the open bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Carnivorous sundew, the bog’s tiny predator', credit:'Photo: Teresa Wang / Pexels'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-from-tower-portrait-latvia.jpg', cap:'A bog pool seen from the tower', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Clouds reflected in a summer bog pool', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'A couple in bog shoes pausing at sunset on the open raised bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'A guest looking out across the bog pools at sunset', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Heading out through the pine forest with bog shoes in hand', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walkers-pool-sunset-latvia.jpg', cap:'Two guests at the bog pool\'s edge watching the sunset', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'https://barefootbaltic.com/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Roland statue in front of the House of Blackheads &mdash; the Old Town’s signature square', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Aerial view of Riga Old Town and the Daugava — the view from the cruise pier', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Narrow cobblestone street through Riga Old Town', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-cat-house/cat-house-bronze-cat-on-turret-detail-riga-latvia.jpg', cap:'The bronze cat on the Cat House turret', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Bastejkalns Canal Park in spring, near the Freedom Monument', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Cobbled inner passage of Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Riga Castle &mdash; the Latvian presidential residence on the Daugava', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cherry blossom in spring at Vermanes Park, Riga’s oldest', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
