// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-walking-trail-overlook-gazebo-latvia.jpg', cap:'Hölzerner Aussichtspavillon am Krimulda-Wanderweg'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Gäste an der Informationstafel des Krimulda-Wanderwegs'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Wanderwege im Gauja-Tal nahe Velnu klints (Teufelsklippen)'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-medieval-castle-guests-posing-latvia.jpg', cap:'Gäste vor der Burgruine der Mittelalterlichen Burg Sigulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Weg zur Burgruine der Mittelalterlichen Burg Sigulda, mit Besuchern'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-bobsled-track-tour-group-latvia.jpg', cap:'Reisegruppe an der olympischen Bob- und Rodelbahn Sigulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Im Burgkomplex Turaida, am Teich des Museumsreservats'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Apfelbaum-Exponat am Volksliederberg Turaida'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Reiseleiterin erklärt in der Mittelalterlichen Burg Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Gäste mit Kerzenlaternen im Inneren der Mittelalterlichen Burg Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-bronze-model-guests-latvia.jpg', cap:'Taktiles Bronzemodell der Burg Cēsis, mit der Reisegruppe'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-walking-tour-guide-latvia.jpg', cap:'Reiseleiterin zeigt Mauerdetails bei der Stadtführung durch die Altstadt von Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-tour-group-photo-latvia.jpg', cap:'Marktplatz der Altstadt von Cēsis, die Reisegruppe fotografiert historische Fassaden'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-walking-tour-latvia.jpg', cap:'Stadtführung durch die Altstadt von Cēsis, Reiseleiterin zeigt ein historisches Gebäude'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-jewish-family-memorial-shoes-latvia.jpg', cap:'Gedenkschuhe vor dem ehemaligen Haus einer im Holocaust ermordeten jüdischen Familie, Altstadt von Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-bronze-sculpture-group-latvia.jpg', cap:'Reisegruppe an der Bronzeskulptur des Pilgers, Altstadtpark von Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-latvia.jpg', cap:'Reisegruppe neben der Bronzeskulptur des Pilgers in Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bakery-bread-tasting-guests-latvia.jpg', cap:'Gäste verkosten frisches Brot in der handwerklichen Bäckerei in Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/barefoot-baltic-van-tasting-daiga-guests-latvia.jpg', cap:'Daiga reicht eine Verkostung an der Seitentür des Barefoot-Baltic-Kleinbusses'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/barefoot-baltic-van-tasting-break-latvia.jpg', cap:'Verkostungspause am Barefoot-Baltic-Kleinbus während der Tour'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga erklärt an einer Informationstafel im Gauja-Tal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga erklärt an einem Aussichtspunkt über das Gauja-Tal mit einer kleinen Reisegruppe'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Reisegruppe am hölzernen Aussichtspavillon Painters&rsquo; Hill über dem Gauja-Tal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Innenraum einer hölzernen Vidzeme-Kirche mit Museumsexponaten und einem Besucher'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Reisegruppe um die Bronzeskulptur des Pilgers in der Altstadt von Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga auf einer Bank an den Brunnen auf dem Vienības laukums, Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Vorführung mit Getreidehalmen für Gäste in der Bäckerei Cēsu Maize'},
    ],
    rundale: [
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Luftaufnahme des Bohlenwegs im Großen Ķemeri-Hochmoor an spiegelglatten Mooraugen vorbei'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Hölzerner Bohlenweg an einem stillen Tümpel im Ķemeri-Hochmoor'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga erklärt an der Burg Bauska'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Prachttreppe von Schloss Rundāle'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Porzellankabinett neben dem Goldenen Saal'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Barocke Rosengärten von Schloss Rundāle im Sommer'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Holzgalerie im Turm der Burg Bauska'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Gast im Turm der Burg Bauska im Winter'},
    ],
    kemeri: [
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Herbstfarben über dem Ķemeri-Hochmoor', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'Blick vom Ķemeri-Aussichtsturm', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'Das Große Ķemeri-Hochmoor von oben im Frühling', credit:'Photo: licensed via iStock'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Letztes Licht auf einer einzelnen Moorkiefer', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sonnenuntergang über den Zwergkiefern von Ķemeri', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'Ein Moorauge in der goldenen Stunde', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Auf dem Rückweg durch den Waldpfad', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'Ein Gast mit Moorschuhen draußen auf dem offenen Hochmoor', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Fleischfressender Sonnentau, der winzige Jäger des Moores', credit:'Photo: Teresa Wang / Pexels'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Wolken spiegeln sich in einem sommerlichen Moorauge', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'Ein Paar in Moorschuhen pausiert bei Sonnenuntergang auf dem offenen Hochmoor', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'Ein Gast blickt bei Sonnenuntergang über die Mooraugen', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Aufbruch durch den Kiefernwald, Moorschuhe in der Hand', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'https://barefootbaltic.com/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Roland statue in front of the House of Blackheads &mdash; the Old Town’s signature square', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Aerial view of Riga Old Town and the Daugava — the view from the cruise pier', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Narrow cobblestone street through Riga Old Town', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Bastejkalns Canal Park in spring, near the Freedom Monument', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Cobbled inner passage of Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Riga Castle &mdash; the Latvian presidential residence on the Daugava', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cherry blossom in spring at Vermanes Park, Riga’s oldest', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
