// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'/images/exc-sigulda/turaida-castle-aerial-red-brick-latvia.jpg', cap:'Turaidas pils &mdash; sarkano ķieģeļu viduslaiku cietoksnis virs Gaujas'},
  {src:'/images/exc-sigulda/cesis-castle-exterior-red-walls-latvia.jpg', cap:'Cēsu pils &mdash; Livonijas ordeņa mītne Vidzemē'},
  {src:'/images/exc-sigulda/gauja-river-bend-aerial-valley-latvia.jpg', cap:'Gaujas upes līkums, Gaujas Nacionālais parks'},
  {src:'/images/exc-sigulda/sigulda-cable-car-gauja-valley-latvia.jpg', cap:'Siguldas gaisa trošu vagoniņš pāri Gaujas ielejas kraujām'},
  {src:'/images/exc-sigulda/cesu-maize-bakery-sign-artisan-bread-latvia.jpg', cap:'Cēsu Maize &mdash; vietējā maize, cepta turpat uz vietas'},
  {src:'/images/exc-sigulda/cesis-castle-walls-autumn-latvia.jpg', cap:'Cēsu pils mūri rudens lapotnē'},
  {src:'/images/exc-sigulda/gauja-river-sunset-valley-latvia.jpg', cap:'Gaujas ieleja saulrietā'},
  {src:'/images/exc-sigulda/cesis-castle-reflection-water-latvia.jpg', cap:'Cēsu pils atspulgs ziemas dīķī'},
  {src:'/images/exc-sigulda/sigulda-barefoot-baltic-van-winter-latvia.jpg', cap:'Barefoot Baltic mikroautobuss ziemā'},
  {src:'/images/exc-sigulda/gauja-river-misty-dawn-autumn-latvia.jpg', cap:'Gaujas upe rītausmā ar paceltos miglu'},
  {src:'/images/exc-sigulda/sigulda-bobsleigh-track-autumn-latvia.jpg', cap:'Siguldas olimpiskā bobsleja trase rudenī'},
  {src:'/images/exc-sigulda/vidzeme-windmill-stone-archway-latvia.jpg', cap:'Vidzemes vējdzirnavas skatā caur akmens arku'},
  {src:'/images/exc-sigulda/vidzeme-orthodox-church-blue-domes-latvia.jpg', cap:'Pareizticīgo baznīca ar zilajiem kupoliem Vidzemes laukos'},
  {src:'/images/exc-sigulda/cesis-st-johns-church-spire-latvia.jpg', cap:'Cēsu Sv. Jāņa baznīca'},
  {src:'/images/exc-sigulda/cesis-castle-autumn-forest-latvia.jpg', cap:'Vidzemes pils rudens meža ielokā'},
  {src:'/images/exc-sigulda/latvia-white-stork-nest-countryside.jpg', cap:'Latvijas baltais stārķis savā ligzdā &mdash; valsts putns'},
  {src:'/images/exc-sigulda/sigulda-rapeseed-field-spring-latvia.jpg', cap:'Rapšu lauks pavasarī, Gaujas ielejā'},
  {src:'/images/exc-sigulda/turaida-castle-museum-reserve-01-latvia.jpg', cap:'Pieeja Turaidas pils koka vārtiem'},
  {src:'/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Turaidas pils iekšpagalmā'},
  {src:'/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Skulptūras par godu Krišjānim Baronam Dainu kalnā'},
  {src:'/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Gaujas ielejas pastaigu takas pie Velnu klintīm'},
  {src:'/images/exc-sigulda/sigulda-new-castle-grounds-01-latvia.jpg', cap:'Siguldas Jaunā pils un apkārtnes parks'},
  {src:'/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Taka uz Siguldas pils viduslaiku drupām'},
  {src:'/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Koka pastaigu taka caur Krimuldas mežu'},
  {src:'/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Cēsu pils iekšiene, apgaismota ar sveču laternu'},
  {src:'/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Mūrniecības detaļas Cēsu pilī'},
  {src:'/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga skaidro pie Gaujas senlejas informācijas stenda'},
  {src:'/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga skaidro Gaujas senlejas skatu vietā ar nelielu tūristu grupu'},
  {src:'/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Tūristu grupa pie Gleznotāju kalna koka skatu altāņa virs Gaujas senlejas'},
  {src:'/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Vidzemes koka baznīcas muzeja interjers ar viesi pie ekspozīcijas'},
  {src:'/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Tūristu grupa ap bronzas svētceļnieka skulptūru Cēsu vecpilsētā'},
  {src:'/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga uz soliņa pie strūklakām Vienības laukumā, Cēsīs'},
  {src:'/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Graudu kūļu demonstrējums viesiem Cēsu Maizes ceptuvē'},
    ],
    rundale: [
  {src:'/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Lielā Ķemeru tīreļa laipa starp tumšajiem purva ezeriņiem no putna lidojuma'},
  {src:'/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Koka laipa gar mierīgu purva ezeriņu Ķemeru augstajā purvā'},
  {src:'/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga stāsta Bauskas pilī'},
  {src:'/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Rundāles pils valsts kāpnes'},
  {src:'/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Porcelāna kabinets pie Zelta zāles'},
  {src:'/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Rundāles pils baroka rožu dārzi vasarā'},
  {src:'/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Koka galerija Bauskas pils tornī'},
  {src:'/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Viesis Bauskas pils tornī ziemā'},
    ],
    kemeri: [
  {src:'/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Autumn colours across the Ķemeri raised bog', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'View from the Ķemeri observation tower', credit:'Photo: source pending, see footer credits'},
  {src:'/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'The Great Ķemeri Bog from above in spring', credit:'Photo: licensed via iStock'},
  {src:'/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Last light on a single bog pine', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sunset over the dwarf pines of Ķemeri', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'A bog pool at golden hour', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Heading back through the forest trail', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'A guest in bog shoes out on the open bog', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Carnivorous sundew, the bog’s tiny predator', credit:'Photo: Teresa Wang / Pexels'},
  {src:'/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Clouds reflected in a summer bog pool', credit:'Photo: source pending, see footer credits'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'A couple in bog shoes pausing at sunset on the open raised bog', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'A guest looking out across the bog pools at sunset', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Heading out through the pine forest with bog shoes in hand', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Roland statue in front of the House of Blackheads &mdash; the Old Town’s signature square', credit:'© Barefoot Baltic'},
  {src:'/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Aerial view of Riga Old Town and the Daugava — the view from the cruise pier', credit:'© Barefoot Baltic'},
  {src:'/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Narrow cobblestone street through Riga Old Town', credit:'© Barefoot Baltic'},
  {src:'/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Bastejkalns Canal Park in spring, near the Freedom Monument', credit:'© Barefoot Baltic'},
  {src:'/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Cobbled inner passage of Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Riga Castle &mdash; the Latvian presidential residence on the Daugava', credit:'© Barefoot Baltic'},
  {src:'/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cherry blossom in spring at Vermanes Park, Riga’s oldest', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
