// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-aerial-red-brick-latvia.jpg', cap:'Turaidos pilis &mdash; raudonų plytų viduramžių tvirtovė virš Gaujos'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-exterior-red-walls-latvia.jpg', cap:'Cēsių pilis &mdash; Livonijos ordino buveinė Vidzemėje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-bend-aerial-valley-latvia.jpg', cap:'Gaujos upės vingis, Gaujos nacionalinis parkas'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-cable-car-gauja-valley-latvia.jpg', cap:'Siguldos keltuvas virš Gaujos slėnio skardžių'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-sign-artisan-bread-latvia.jpg', cap:'Česu Maize &mdash; vietinė duona, kepama čia pat'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-walls-autumn-latvia.jpg', cap:'Cēsių pilies sienos rudens lapijoje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-sunset-valley-latvia.jpg', cap:'Gaujos slėnis saulėlydyje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-reflection-water-latvia.jpg', cap:'Cēsių pilies atspindys žiemos tvenkinyje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-barefoot-baltic-van-winter-latvia.jpg', cap:'Barefoot Baltic mikroautobusas žiemą'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-misty-dawn-autumn-latvia.jpg', cap:'Gaujos upė auštant, kylant rūkui'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-bobsleigh-track-autumn-latvia.jpg', cap:'Siguldos olimpinė bobslėjaus trasa rudenį'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-windmill-stone-archway-latvia.jpg', cap:'Vidzemės vėjo malūnas, žvelgiant pro akmens arką'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-orthodox-church-blue-domes-latvia.jpg', cap:'Stačiatikių cerkvė mėlynais kupolais Vidzemės kaimo apylinkėse'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-st-johns-church-spire-latvia.jpg', cap:'Cēsių Šv. Jono bažnyčia'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-autumn-forest-latvia.jpg', cap:'Vidzemės pilis rudens miško apsuptyje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/latvia-white-stork-nest-countryside.jpg', cap:'Latvijos baltasis gandras savo lizde &mdash; valstybės paukštis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-rapeseed-field-spring-latvia.jpg', cap:'Žydintis rapsų laukas pavasarį, Gaujos slėnis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-01-latvia.jpg', cap:'Priėjimas prie medinių Turaidos pilies vartų'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Turaidos pilies vidiniame kieme'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Skulptūros, pagerbiančios Krišjānį Baroną Dainų kalne'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Gaujos slėnio pasivaikščiojimo takai prie Velnu klints (Velnio uolos)'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-01-latvia.jpg', cap:'Siguldos Naujieji rūmai ir aplinkinis parkas'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Takas link Siguldos pilies viduramžių griuvėsių'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Medinis pasivaikščiojimo takas per Krimuldos mišką'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Cēsių pilies vidus, apšviestas žvakių žibinto'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Mūro detalė Cēsių pilyje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga aiškina prie Gaujos slėnio informacinio stendo'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga aiškina Gaujos slėnio apžvalgos vietoje su nedidele grupe'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Grupė prie medinės Painters&rsquo; Hill apžvalgos pavėsinės virš Gaujos slėnio'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Vidzemės medinės bažnyčios muziejaus vidus su lankytoju prie ekspozicijos'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Grupė aplink bronzinę piligrimo skulptūrą Cēsių senamiestyje'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga ant suolelio prie fontanų Vienības laukume, Cēsiai'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Grūdų pėdų demonstravimas svečiams Cēsu Maize kepykloje'},
    ],
    rundale: [
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Vaizdas iš oro į Didžiosios Kemerių pelkės lentinį taką pro tamsius veidrodinius klanus'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Medinis lentinis takas, einantis pro ramų klaną Kemerių aukštapelkėje'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga pasakoja prie Bauskės pilies'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Rundalės rūmų iškilmingieji laiptai'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Porceliano kabinetas šalia Auksinės salės'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Rundalės rūmų baroko rožių sodai vasarą'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Medinė galerija Bauskės pilies bokšte'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Svečias Bauskės pilies bokšte žiemą'},
    ],
    kemeri: [
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Autumn colours across the Ķemeri raised bog', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'View from the Ķemeri observation tower', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'The Great Ķemeri Bog from above in spring', credit:'Photo: licensed via iStock'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Last light on a single bog pine', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sunset over the dwarf pines of Ķemeri', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'A bog pool at golden hour', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Heading back through the forest trail', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'A guest in bog shoes out on the open bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Carnivorous sundew, the bog’s tiny predator', credit:'Photo: Teresa Wang / Pexels'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Clouds reflected in a summer bog pool', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'A couple in bog shoes pausing at sunset on the open raised bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'A guest looking out across the bog pools at sunset', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Heading out through the pine forest with bog shoes in hand', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'https://barefootbaltic.com/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Roland statue in front of the House of Blackheads &mdash; the Old Town’s signature square', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Aerial view of Riga Old Town and the Daugava — the view from the cruise pier', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Narrow cobblestone street through Riga Old Town', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Bastejkalns Canal Park in spring, near the Freedom Monument', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Cobbled inner passage of Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Riga Castle &mdash; the Latvian presidential residence on the Daugava', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cherry blossom in spring at Vermanes Park, Riga’s oldest', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
