// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-walking-trail-overlook-gazebo-latvia.jpg', cap:'Drewniana altana widokowa na&nbsp;szlaku spacerowym Krimulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Goście przy tablicy informacyjnej szlaku Krimulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Szlaki doliny Gauji w&nbsp;okolicy Velnu klints (Klifów Diabła)'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-medieval-castle-guests-posing-latvia.jpg', cap:'Goście przed ruinami średniowiecznego zamku Sigulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Ścieżka do&nbsp;ruin średniowiecznego zamku Sigulda, z&nbsp;odwiedzającymi'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-bobsled-track-tour-group-latvia.jpg', cap:'Grupa wycieczkowa przy olimpijskim torze bobslejowym i&nbsp;saneczkowym Sigulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Wewnątrz kompleksu zamku Turaida, nad stawem rezerwatu muzealnego'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Ekspozycja jabłoni na&nbsp;Wzgórzu Pieśni Ludowych Turaida'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Przewodnik objaśniający w&nbsp;średniowiecznym zamku Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Goście ze&nbsp;świecznikowymi latarniami we&nbsp;wnętrzu średniowiecznego zamku Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-bronze-model-guests-latvia.jpg', cap:'Dotykowy brązowy model zamku Cēsis, z&nbsp;grupą wycieczkową'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-walking-tour-guide-latvia.jpg', cap:'Przewodnik wskazujący detale murów podczas spaceru po&nbsp;starym mieście Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-tour-group-photo-latvia.jpg', cap:'Rynek starego miasta Cēsis, grupa wycieczkowa fotografująca zabytkowe fasady'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-walking-tour-latvia.jpg', cap:'Spacer po&nbsp;starym mieście Cēsis, przewodnik wskazujący zabytkowy budynek'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-jewish-family-memorial-shoes-latvia.jpg', cap:'Pamiątkowe buty przed dawnym domem żydowskiej rodziny zamordowanej w&nbsp;Holokauście, stare miasto Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-bronze-sculpture-group-latvia.jpg', cap:'Grupa wycieczkowa przy brązowej rzeźbie pielgrzyma, park starego miasta Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-latvia.jpg', cap:'Grupa wycieczkowa obok brązowej rzeźby pielgrzyma w&nbsp;Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bakery-bread-tasting-guests-latvia.jpg', cap:'Goście próbujący świeżego chleba w&nbsp;rzemieślniczej piekarni w&nbsp;Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/barefoot-baltic-van-tasting-daiga-guests-latvia.jpg', cap:'Daiga podająca degustację przy bocznych drzwiach busa Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/barefoot-baltic-van-tasting-break-latvia.jpg', cap:'Przerwa degustacyjna przy busie Barefoot Baltic podczas wycieczki'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga objaśniająca przy tablicy informacyjnej w&nbsp;Dolinie Gaui'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga objaśniająca w&nbsp;punkcie widokowym nad Doliną Gaui z&nbsp;małą grupą gości'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Grupa gości przy drewnianej altanie widokowej Painters&rsquo; Hill nad Doliną Gaui'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Wnętrze drewnianego muzeum-kościoła Vidzeme z&nbsp;gościem oglądającym ekspozycję'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Grupa gości wokół brązowej rzeźby pielgrzyma na starówce w&nbsp;Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga na ławce obok fontann na Vienības laukums, Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Pokaz snopów zboża dla gości w&nbsp;piekarni Cēsu Maize'},
    ],
    rundale: [
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Widok z lotu ptaka na pomost Wielkiego Torfowiska Ķemeri obok lustrzano-ciemnych oczek'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Drewniany pomost wzdłuż spokojnego stawu na torfowisku wysokim Ķemeri'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga opowiada w zamku Bauska'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Reprezentacyjna klatka schodowa Pałacu Rundāle'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Gabinet porcelany obok Złotej Sali'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Barokowe ogrody różane Pałacu Rundāle latem'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Drewniana galeria w wieży zamku Bauska'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Gość na wieży zamku Bauska zimą'},
    ],
    kemeri: [
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Jesienne kolory na torfowisku wysokim Ķemeri', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'Widok z wieży widokowej w Ķemeri', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'Wielkie Torfowisko Ķemeri z góry wiosną', credit:'Photo: licensed via iStock'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Ostatnie światło na samotnej sośnie torfowiskowej', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Zachód słońca nad karłowatymi sosnami Ķemeri', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'Pływacz torfowiskowy w złotej godzinie', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Powrót leśną ścieżką', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'Gość w butach bagiennych na otwartym torfowisku', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Mięsożerna rosiczka, malutki drapieżnik torfowiska', credit:'Photo: Teresa Wang / Pexels'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Chmury odbite w letnim pływaczu torfowiskowym', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'Para w butach bagiennych w chwili postoju o zachodzie słońca na otwartym torfowisku wysokim', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'Gość patrzący na pływacze torfowiska o zachodzie słońca', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Marsz przez sosnowy las z butami bagiennymi w ręku', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'https://barefootbaltic.com/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Pomnik Rolanda przed Domem Czarnogłowych &mdash; charakterystyczny rynek Starego Miasta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Widok z lotu ptaka na Stare Miasto w Rydze i Dźwinę &mdash; widok z nabrzeża wycieczkowego', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Wąska brukowana uliczka na Starym Mieście w Rydze', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Park Bastejkalns wiosną, w pobliżu Pomnika Wolności', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Brukowany pasaż wewnętrzny Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Zamek Ryski &mdash; łotewska rezydencja prezydencka nad Dźwiną', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Kwitnące wiśnie wiosną w Parku Vermanes, najstarszym w Rydze', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
