// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-aerial-red-brick-latvia.jpg', cap:'Castillo de Turaida, la fortaleza medieval de ladrillo rojo sobre el Gauja'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-exterior-red-walls-latvia.jpg', cap:'Castillo de Cēsis, la sede de la Orden de Livonia en Vidzeme'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-bend-aerial-valley-latvia.jpg', cap:'Curva del río Gauja, Parque Nacional del valle del Gauja'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-cable-car-gauja-valley-latvia.jpg', cap:'El teleférico de Sigulda sobre los acantilados del valle del Gauja'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-sign-artisan-bread-latvia.jpg', cap:'Česu Maize, pan local hecho aquí mismo'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-walls-autumn-latvia.jpg', cap:'Murallas del castillo de Cēsis enmarcadas por hojas de otoño'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-sunset-valley-latvia.jpg', cap:'El valle del Gauja al atardecer'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-reflection-water-latvia.jpg', cap:'El castillo de Cēsis reflejado en el estanque invernal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-barefoot-baltic-van-winter-latvia.jpg', cap:'La furgoneta de Barefoot Baltic en invierno'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-river-misty-dawn-autumn-latvia.jpg', cap:'El río Gauja al amanecer con niebla levantándose'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-bobsleigh-track-autumn-latvia.jpg', cap:'La pista olímpica de bobsleigh de Sigulda en otoño'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-windmill-stone-archway-latvia.jpg', cap:'Un molino de Vidzeme visto a través de un arco de piedra'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-orthodox-church-blue-domes-latvia.jpg', cap:'Una iglesia ortodoxa de cúpulas azules en el campo de Vidzeme'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-st-johns-church-spire-latvia.jpg', cap:'Iglesia de San Juan de Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-autumn-forest-latvia.jpg', cap:'Un castillo de Vidzeme enmarcado por bosque otoñal'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/latvia-white-stork-nest-countryside.jpg', cap:'Un nido de cigüeña blanca letona, el ave nacional'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-rapeseed-field-spring-latvia.jpg', cap:'Un campo de colza en flor, primavera en el valle del Gauja'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-01-latvia.jpg', cap:'Acceso a la entrada de madera del castillo de Turaida'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'En el patio del castillo de Turaida'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Esculturas en honor a Krišjānis Barons en la Colina de las Canciones'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Senderos del valle del Gauja cerca de Velnu klints (Acantilados del Diablo)'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-01-latvia.jpg', cap:'Sigulda New Castle y el parque que lo rodea'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Camino a las ruinas medievales del castillo de Sigulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Camino de madera por el bosque de Krimulda'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Interior del castillo de Cēsis, iluminado con linterna de vela'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Detalle de la mampostería en el interior del castillo de Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga explicando junto a un panel informativo del valle del Gauja'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga explicando en un mirador del valle del Gauja con un grupo pequeño'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Grupo en el mirador de madera de Painters&rsquo; Hill sobre el valle del Gauja'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Interior del museo-iglesia de madera de Vidzeme con un visitante ante las vitrinas'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Grupo en torno a la escultura de bronce del peregrino en el casco antiguo de Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga en un banco junto a las fuentes de la plaza Vienības laukums, Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Demostración con manojos de cereales para los huéspedes en la panadería Cēsu Maize'},
    ],
    rundale: [
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Vista aérea de la pasarela de la Gran turbera de Ķemeri pasando entre charcas oscuras como espejos'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Pasarela de madera bordeando una charca tranquila en la turbera elevada de Ķemeri'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga explicando en el castillo de Bauska'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Escalera de honor del palacio de Rundāle'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Gabinete de porcelana junto a la Sala de Oro'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Jardines barrocos de rosas en verano'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Galería de madera en la torre de Bauska'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Visitante en la torre de Bauska en invierno'},
    ],
    kemeri: [
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Autumn colours across the Ķemeri raised bog', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'View from the Ķemeri observation tower', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'The Great Ķemeri Bog from above in spring', credit:'Photo: licensed via iStock'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Last light on a single bog pine', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sunset over the dwarf pines of Ķemeri', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'A bog pool at golden hour', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Heading back through the forest trail', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'A guest in bog shoes out on the open bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Carnivorous sundew, the bog’s tiny predator', credit:'Photo: Teresa Wang / Pexels'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Clouds reflected in a summer bog pool', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'A couple in bog shoes pausing at sunset on the open raised bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'A guest looking out across the bog pools at sunset', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Heading out through the pine forest with bog shoes in hand', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'https://barefootbaltic.com/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Roland statue in front of the House of Blackheads &mdash; the Old Town’s signature square', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Aerial view of Riga Old Town and the Daugava — the view from the cruise pier', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Narrow cobblestone street through Riga Old Town', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Bastejkalns Canal Park in spring, near the Freedom Monument', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Cobbled inner passage of Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Riga Castle &mdash; the Latvian presidential residence on the Daugava', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cherry blossom in spring at Vermanes Park, Riga’s oldest', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
