// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-walking-trail-overlook-gazebo-latvia.jpg', cap:'Wooden overlook gazebo on the Krimulda walking trail'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Guests at the Krimulda walking trail information display'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Gauja Valley walking trails near Velnu klints (Devil&rsquo;s Cliffs)'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-medieval-castle-guests-posing-latvia.jpg', cap:'Guests in front of the Sigulda Medieval Castle ruins'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Path to the Sigulda Medieval Castle ruins, with visitors'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-bobsled-track-tour-group-latvia.jpg', cap:'Tour group at the Sigulda Olympic bobsled and luge track'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Inside the Turaida Castle complex, by the museum-reserve pond'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Apple-tree exhibit on the Turaida Folk Songs Hill'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Guide explaining at Cēsis Medieval Castle'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Guests with candle lanterns inside Cēsis Medieval Castle'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-castle-bronze-model-guests-latvia.jpg', cap:'Tactile bronze model of Cēsis Castle, with the tour group'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-walking-tour-guide-latvia.jpg', cap:'Guide pointing out wall details on the Cēsis old-town walking tour'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-tour-group-photo-latvia.jpg', cap:'Cēsis old town square, the tour group photographing heritage facades'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-walking-tour-latvia.jpg', cap:'Cēsis old-town walking tour, guide pointing out a heritage building'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-jewish-family-memorial-shoes-latvia.jpg', cap:'Memorial shoes outside the former home of a Jewish family murdered in the Holocaust, Cēsis old town'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-bronze-sculpture-group-latvia.jpg', cap:'Tour group at the bronze pilgrim sculpture, Cēsis old town park'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-latvia.jpg', cap:'Tour group beside the bronze pilgrim sculpture in Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bakery-bread-tasting-guests-latvia.jpg', cap:'Guests sampling fresh bread at the Cēsis artisan bakery'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/barefoot-baltic-van-tasting-daiga-guests-latvia.jpg', cap:'Daiga handing out a tasting at the side door of the Barefoot Baltic van'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/barefoot-baltic-van-tasting-break-latvia.jpg', cap:'Tasting break at the Barefoot Baltic van during the tour'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga explaining at a Gauja Valley tour information panel'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga explaining at a Gauja Valley overlook with a small tour group'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Tour group at the Painters&rsquo; Hill wooden overlook gazebo above the Gauja Valley'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Wooden Vidzeme heritage church museum interior with a guest viewing exhibits'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Tour group around the bronze pilgrim sculpture in Cēsis old town'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga on a bench beside the fountains on Vienības laukums, Cēsis'},
  {src:'https://barefootbaltic.com/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Grain-stalks demonstration to guests inside the Cēsu Maize bakery'},
    ],
    rundale: [
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Aerial view of the Great Ķemeri Bog boardwalk past mirror-dark pools'},
  {src:'https://barefootbaltic.com/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Wooden boardwalk skirting a still pond in the Ķemeri raised bog'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga explaining at Bauska Castle'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Rundāle Palace state staircase'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Porcelain cabinet beside the Gold Hall'},
  {src:'https://barefootbaltic.com/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Rundāle Palace baroque rose gardens in summer'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Wooden gallery in the Bauska Castle tower'},
  {src:'https://barefootbaltic.com/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Guest at Bauska Castle tower in winter'},
    ],
    kemeri: [
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Autumn colours across the Ķemeri raised bog', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'View from the Ķemeri observation tower', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'The Great Ķemeri Bog from above in spring', credit:'Photo: licensed via iStock'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Last light on a single bog pine', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sunset over the dwarf pines of Ķemeri', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'A bog pool at golden hour', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Heading back through the forest trail', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'A guest in bog shoes out on the open bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Carnivorous sundew, the bog’s tiny predator', credit:'Photo: Teresa Wang / Pexels'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Clouds reflected in a summer bog pool', credit:'Photo: source pending, see footer credits'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'A couple in bog shoes pausing at sunset on the open raised bog', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'A guest looking out across the bog pools at sunset', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Heading out through the pine forest with bog shoes in hand', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'https://barefootbaltic.com/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Estátua de Rolando em frente à Casa das Cabeças Negras &mdash; a praça emblemática do centro histórico', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Vista aérea do centro histórico de Riga e do Daugava — a vista do cais de cruzeiros', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Rua estreita de calçada pelo centro histórico de Riga', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Parque-canal de Bastejkalns na primavera, perto do Monumento da Liberdade', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Passagem interior em calçada de Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Castelo de Riga &mdash; a residência presidencial da Letónia no Daugava', credit:'© Barefoot Baltic'},
  {src:'https://barefootbaltic.com/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cerejeiras em flor na primavera no Parque de Vērmane, o mais antigo de Riga', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
