// Auto-generated by scripts/build_tile_shuffle.py — DO NOT EDIT BY HAND.
// Picks a random photo from each excursion's lightbox set and swaps it into
// the matching homepage tile on page load. Images render with
// object-fit:contain so the full photo is always visible, letterboxed
// against the tile's sand background — never cropped.
(function () {
  var TILE_PHOTOS = {
    sigulda: [
  {src:'/images/exc-sigulda/turaida-castle-aerial-red-brick-latvia.jpg', cap:'Le château de Turaida, la forteresse médiévale en brique rouge au-dessus de la Gauja'},
  {src:'/images/exc-sigulda/cesis-castle-exterior-red-walls-latvia.jpg', cap:'Le château de Cēsis, siège de l&rsquo;Ordre livonien en Vidzeme'},
  {src:'/images/exc-sigulda/gauja-river-bend-aerial-valley-latvia.jpg', cap:'Le méandre de la Gauja, parc national de la vallée de la Gauja'},
  {src:'/images/exc-sigulda/sigulda-cable-car-gauja-valley-latvia.jpg', cap:'Le téléphérique de Sigulda traversant les falaises de la vallée de la Gauja'},
  {src:'/images/exc-sigulda/cesu-maize-bakery-sign-artisan-bread-latvia.jpg', cap:'Česu Maize, pain local, cuit sur place'},
  {src:'/images/exc-sigulda/cesis-castle-walls-autumn-latvia.jpg', cap:'Les murs du château de Cēsis encadrés par les feuilles d&rsquo;automne'},
  {src:'/images/exc-sigulda/gauja-river-sunset-valley-latvia.jpg', cap:'La vallée de la Gauja au coucher du soleil'},
  {src:'/images/exc-sigulda/cesis-castle-reflection-water-latvia.jpg', cap:'Le château de Cēsis se reflétant dans l&rsquo;étang d&rsquo;hiver'},
  {src:'/images/exc-sigulda/sigulda-barefoot-baltic-van-winter-latvia.jpg', cap:'Le van Barefoot Baltic en hiver'},
  {src:'/images/exc-sigulda/gauja-river-misty-dawn-autumn-latvia.jpg', cap:'La rivière Gauja à l&rsquo;aube avec la brume qui se lève'},
  {src:'/images/exc-sigulda/sigulda-bobsleigh-track-autumn-latvia.jpg', cap:'La piste olympique de bobsleigh de Sigulda en automne'},
  {src:'/images/exc-sigulda/vidzeme-windmill-stone-archway-latvia.jpg', cap:'Un moulin de Vidzeme aperçu à travers une voûte de pierre'},
  {src:'/images/exc-sigulda/vidzeme-orthodox-church-blue-domes-latvia.jpg', cap:'Une église orthodoxe aux dômes bleus dans la campagne de Vidzeme'},
  {src:'/images/exc-sigulda/cesis-st-johns-church-spire-latvia.jpg', cap:'L&rsquo;église Saint-Jean de Cēsis'},
  {src:'/images/exc-sigulda/cesis-castle-autumn-forest-latvia.jpg', cap:'Un château de Vidzeme encadré par la forêt d&rsquo;automne'},
  {src:'/images/exc-sigulda/latvia-white-stork-nest-countryside.jpg', cap:'Un nid de cigogne blanche, l&rsquo;oiseau national de la Lettonie'},
  {src:'/images/exc-sigulda/sigulda-rapeseed-field-spring-latvia.jpg', cap:'Un champ de colza en fleur, le printemps dans la vallée de la Gauja'},
  {src:'/images/exc-sigulda/turaida-castle-museum-reserve-01-latvia.jpg', cap:'Approche de la porte en bois du château de Turaida'},
  {src:'/images/exc-sigulda/turaida-castle-museum-reserve-10-latvia.jpg', cap:'Dans la cour du château de Turaida'},
  {src:'/images/exc-sigulda/turaida-folk-songs-hill-3-latvia.jpg', cap:'Sculptures en l\'honneur de Krišjānis Barons à la Colline des chants populaires'},
  {src:'/images/exc-sigulda/gauja-valley-walking-trails-sigulda-1-latvia.jpg', cap:'Sentiers de la vallée de la Gauja près de Velnu klints (Falaises du Diable)'},
  {src:'/images/exc-sigulda/sigulda-new-castle-grounds-01-latvia.jpg', cap:'Le château neuf de Sigulda et son parc'},
  {src:'/images/exc-sigulda/sigulda-new-castle-grounds-08-latvia.jpg', cap:'Chemin vers les ruines médiévales du château de Sigulda'},
  {src:'/images/exc-sigulda/krimulda-gauja-valley-01-latvia.jpg', cap:'Chemin en bois à travers la forêt de Krimulda'},
  {src:'/images/exc-sigulda/cesis-medieval-castle-day1-1-latvia.jpg', cap:'Intérieur du château de Cēsis, éclairé à la lanterne'},
  {src:'/images/exc-sigulda/cesis-medieval-castle-day1-5-latvia.jpg', cap:'Détail de la maçonnerie à l\'intérieur du château de Cēsis'},
  {src:'/images/exc-sigulda/gauja-valley-tour-daiga-explaining-info-panel-latvia.jpg', cap:'Daiga commente devant un panneau d&rsquo;information de la vallée de la Gauja'},
  {src:'/images/exc-sigulda/sigulda-gauja-overlook-daiga-explaining-group-latvia.jpg', cap:'Daiga commente à un belvédère sur la vallée de la Gauja avec un petit groupe'},
  {src:'/images/exc-sigulda/sigulda-gauja-painters-hill-gazebo-overlook-group-latvia.jpg', cap:'Groupe au pavillon-belvédère en bois de Painters&rsquo; Hill au-dessus de la vallée de la Gauja'},
  {src:'/images/exc-sigulda/vidzeme-wooden-church-museum-interior-guest-latvia.jpg', cap:'Intérieur du musée-église en bois de Vidzeme, un visiteur devant les expositions'},
  {src:'/images/exc-sigulda/cesis-bronze-pilgrim-tour-group-2-latvia.jpg', cap:'Groupe autour de la sculpture en bronze du pèlerin dans la vieille ville de Cēsis'},
  {src:'/images/exc-sigulda/cesis-old-town-square-daiga-bench-portrait-latvia.jpg', cap:'Daiga sur un banc près des fontaines de la place Vienības laukums, Cēsis'},
  {src:'/images/exc-sigulda/cesu-maize-bakery-grain-stalks-demo-guests-latvia.jpg', cap:'Démonstration de gerbes de céréales pour les invités à la boulangerie Cēsu Maize'},
    ],
    rundale: [
  {src:'/images/exc-rundale/kemeri-bog-aerial-spring-latvia.jpg', cap:'Vue aérienne de la passerelle de la Grande tourbière de Ķemeri longeant des étangs miroirs sombres'},
  {src:'/images/exc-rundale/kemeri-boardwalk-pond-latvia.jpg', cap:'Passerelle en bois longeant un étang calme dans la tourbière haute de Ķemeri'},
  {src:'/images/exc-rundale/bauska-castle-daiga-guide-explaining-latvia.jpg', cap:'Daiga raconte au château de Bauska'},
  {src:'/images/exc-rundale/rundale-palace-state-staircase-04-latvia.jpg', cap:'Escalier d\'honneur du château de Rundāle'},
  {src:'/images/exc-rundale/rundale-palace-porcelain-cabinet-gold-hall-3-latvia.jpg', cap:'Cabinet de porcelaine près de la Salle d\'or'},
  {src:'/images/exc-rundale/rundale-palace-baroque-rose-gardens-latvia.jpg', cap:'Jardins de roses baroques en été'},
  {src:'/images/exc-rundale/bauska-castle-tower-wooden-gallery-latvia.jpg', cap:'Galerie en bois de la tour de Bauska'},
  {src:'/images/exc-rundale/bauska-castle-tower-winter-view-guest-latvia.jpg', cap:'Voyageur à la tour de Bauska en hiver'},
    ],
    kemeri: [
  {src:'/images/exc-kemeri/kemeri-bog-aerial-autumn-latvia.jpg', cap:'Autumn colours across the Ķemeri raised bog', credit:'Photo: Liga Meijere / Unsplash'},
  {src:'/images/exc-kemeri/kemeri-bog-aerial-from-tower-summer-latvia.jpg', cap:'View from the Ķemeri observation tower', credit:'Photo: source pending, see footer credits'},
  {src:'/images/exc-kemeri/kemeri-bog-aerial-spring-latvia.jpg', cap:'The Great Ķemeri Bog from above in spring', credit:'Photo: licensed via iStock'},
  {src:'/images/exc-kemeri/kemeri-bog-sunset-pine-closeup-latvia.jpg', cap:'Last light on a single bog pine', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-sunset-pines-latvia.jpg', cap:'Sunset over the dwarf pines of Ķemeri', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-sunset-pond-latvia.jpg', cap:'A bog pool at golden hour', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-forest-trail-latvia.jpg', cap:'Heading back through the forest trail', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-walker-solo-latvia.jpg', cap:'A guest in bog shoes out on the open bog', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-sundew-latvia.jpg', cap:'Carnivorous sundew, the bog’s tiny predator', credit:'Photo: Teresa Wang / Pexels'},
  {src:'/images/exc-kemeri/kemeri-bog-pond-summer-clouds-latvia.jpg', cap:'Clouds reflected in a summer bog pool', credit:'Photo: source pending, see footer credits'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-couple-pools-sunset-latvia.jpg', cap:'A couple in bog shoes pausing at sunset on the open raised bog', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-pools-sunset-walker-latvia.jpg', cap:'A guest looking out across the bog pools at sunset', credit:'© Barefoot Baltic'},
  {src:'/images/exc-kemeri/kemeri-bog-shoe-forest-walk-latvia.jpg', cap:'Heading out through the pine forest with bog shoes in hand', credit:'© Barefoot Baltic'},
    ],
    'riga-shore': [
  {src:'/images/riga-roland-statue-house-of-blackheads-latvia.jpg', cap:'Roland statue in front of the House of Blackheads &mdash; the Old Town’s signature square', credit:'© Barefoot Baltic'},
  {src:'/images/riga-old-town-aerial-daugava-river-latvia.jpg', cap:'Aerial view of Riga Old Town and the Daugava — the view from the cruise pier', credit:'© Barefoot Baltic'},
  {src:'/images/riga-old-town-cobblestone-street-restaurants-latvia.jpg', cap:'Narrow cobblestone street through Riga Old Town', credit:'© Barefoot Baltic'},
  {src:'/images/blog-freedom-monument/bastejkalns-canal-park-spring-riga-latvia.jpg', cap:'Bastejkalns Canal Park in spring, near the Freedom Monument', credit:'© Barefoot Baltic'},
  {src:'/images/blog-konventa-seta/konventa-seta-cobbled-inner-passage-riga-latvia.jpg', cap:'Cobbled inner passage of Konventa Sēta', credit:'© Barefoot Baltic'},
  {src:'/images/blog-riga-castle/riga-castle-presidential-residence-side-view-latvia.jpg', cap:'Riga Castle &mdash; the Latvian presidential residence on the Daugava', credit:'© Barefoot Baltic'},
  {src:'/images/blog-vermanes-darzs/vermanes-darzs-cherry-blossom-spring-riga-latvia.jpg', cap:'Cherry blossom in spring at Vermanes Park, Riga’s oldest', credit:'© Barefoot Baltic'}
    ]
  };
  var CROP_TO_KEY = {
    'crop-sigulda':    'sigulda',
    'crop-rundale':    'rundale',
    'crop-kemeri':     'kemeri',
    'crop-riga-shore': 'riga-shore'
  };
  function init() {
    document.querySelectorAll('#excursions .exc-card-img').forEach(function (div) {
      var key = null;
      for (var cls in CROP_TO_KEY) {
        if (div.classList.contains(cls)) { key = CROP_TO_KEY[cls]; break; }
      }
      if (!key) return;
      var photos = TILE_PHOTOS[key];
      if (!photos || !photos.length) return;
      var pick = photos[Math.floor(Math.random() * photos.length)];
      var picture = div.querySelector('picture');
      if (!picture) return;
      var source = picture.querySelector('source[type="image/webp"]');
      var img = picture.querySelector('img');
      var webp = pick.src.replace(/\.(jpe?g|webp)$/i, '.webp');
      var jpg  = pick.src.replace(/\.(jpe?g|webp)$/i, '.jpg');
      if (source) source.srcset = webp;
      if (img) {
        img.src = jpg;
        if (pick.cap) img.alt = pick.cap;
        // object-fit:contain shows the entire image, letterboxed against
        // the tile's sand background — no cropping at any breakpoint.
        // Clear any stale object-position from a previous swap.
        img.style.objectFit = 'contain';
        img.style.removeProperty('object-position');
      }
    });
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
